name: Generate Keystore (ONE TIME)

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Generate keystore
        run: |
          keytool -genkey -v \
            -keystore my-release-key.keystore \
            -alias mayumsyka2 \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -storepass mayumsyka \
            -keypass mayumsyka \
            -dname "CN=MayUmshka2, OU=Game, O=MyRunPlay, L=Moscow, S=Moscow, C=RU"

      - name: Convert to base64
        run: |
          base64 -w 0 my-release-key.keystore > keystore.b64
          echo ""
          echo "=========================================="
          echo "СКОПИРУЙТЕ СТРОКУ НИЖЕ В СЕКРЕТ KEYSTORE_BASE64"
          echo "=========================================="
          cat keystore.b64
          echo ""
          echo "=========================================="

      - name: Upload keystore file
        uses: actions/upload-artifact@v4
        with:
          name: KEYSTORE-FILE-SAVE-IT
          path: my-release-key.keystore
